project:
  type: book
  output-dir: docs

bibliography: library/references.bib

date: 2026-08-01
date-format: "MMM YYYY"

book:
  title: "Data Science Foundations System"
  subtitle: "A Reusable Python Workflow for Tidy Data Analysis and Interpretation"
  author: "Teresia Mrema Buza | Complex Data Insights"
  chapters:
    - index.qmd

    - part: "System Orientation"
      chapters:
        - 00-preface.qmd
        - 01-setting-up-environment.qmd

    - part: "Data Inspection and Preparation"
      chapters:
        - 02-load-and-explore-dataset.qmd
        - 03-data-cleaning-and-preparation.qmd

    - part: "Data Transformation and Analysis"
      chapters:
        - 04-data-wrangling-basics.qmd
        - 05-visualization-basics.qmd
        - 06-summary-statistics-and-insights.qmd

    - part: "From Analysis to Modeling"
      chapters:
        - 07-from-analysis-to-ml.qmd

    - part: "Reference"
      chapters:
        - 999-appendix.qmd
        - 999-references.qmd

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    number-depth: 2
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    css: assets/css/cdi.css
    code-fold: true
    mermaid:
      theme: forest

execute:
  echo: true
  warning: false
  message: false
  freeze: auto
  working-dir: .
